server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

  - job_name: flask
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask
          __path__: /var/log/badbeatstools/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            traceID: trace_id
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          traceID:
      - output:
          source: message

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*log
    pipeline_stages:
      - regex:
          expression: '^(?P<ip>\\S+) (?P<identd>\\S+) (?P<user>\\S+) \\[(?P<timestamp>[\\w:/]+\\s[+\\-]\\d{4})\\] "(?P<method>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?" (?P<status>\\d{3}|-) (?P<size>\\d+|-)\\s?"?(?P<referer>[^"]*)"?\\s?"?(?P<agent>[^"]*)"?$'
      - timestamp:
          source: timestamp
          format: 02/Jan/2006:15:04:05 -0700
      - labels:
          status:
          method:
          path:

  - job_name: postgres
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: /var/log/postgresql/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}.\\d{3} \\w+) \\[(?P<pid>\\d+)\\] (?P<level>\\w+): (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000 MST
      - labels:
          level:
      - output:
          source: message

  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /var/log/redis/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\\d{2} \\w{3} \\d{2}:\\d{2}:\\d{2}\\.\\d{3}) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 02 Jan 15:04:05.000
      - output:
          source: message
