global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@badbeatstools.io'
  smtp_auth_username: 'alerts@badbeatstools.io'
  smtp_auth_password: 'your-app-specific-password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    - match:
        severity: warning
      receiver: 'warning-alerts'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        icon_url: 'https://badbeatstools.io/assets/alert-icon.png'
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.default.titlelink" . }}'

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@badbeatstools.io'
        send_resolved: true
    slack_configs:
      - channel: '#critical-alerts'
        send_resolved: true
        icon_url: 'https://badbeatstools.io/assets/critical-icon.png'
        title: '🚨 CRITICAL ALERT: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'alerts@badbeatstools.io'
        send_resolved: true
    slack_configs:
      - channel: '#warning-alerts'
        send_resolved: true
        icon_url: 'https://badbeatstools.io/assets/warning-icon.png'
        title: '⚠️ WARNING: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

templates:
  - '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
